[pytest]
testpaths =
    packages/agent
    packages/agent-asr
    packages/agent-ocr
    packages/agent-triage
    packages/api

addopts =
    --import-mode=importlib
    --cov
    --cov-report=term-missing

# Python files to search for tests
python_files = test_*.py

# Test classes to discover
python_classes = Test*

# Test functions to discover
python_functions = test_*

asyncio_mode = auto
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session
